{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-6892", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "cloudme", "product": {"product_data": [{"product_name": "sync", "version": {"version_data": [{"version_value": "1.10.9", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-119"}]}]}, "references": {"reference_data": [{"url": "http://hyp3rlinx.altervista.org/advisories/CLOUDME-SYNC-UNAUTHENTICATED-REMOTE-BUFFER-OVERFLOW.txt", "name": "http://hyp3rlinx.altervista.org/advisories/CLOUDME-SYNC-UNAUTHENTICATED-REMOTE-BUFFER-OVERFLOW.txt", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}, {"url": "https://blogs.securiteam.com/index.php/archives/3669", "name": "https://blogs.securiteam.com/index.php/archives/3669", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}, {"url": "https://www.exploit-db.com/exploits/44027/", "name": "44027", "refsource": "EXPLOIT-DB", "tags": ["Exploit", "Third Party Advisory", "VDB Entry"]}, {"url": "https://www.exploit-db.com/exploits/44175/", "name": "44175", "refsource": "EXPLOIT-DB", "tags": ["Exploit", "Third Party Advisory", "VDB Entry"]}, {"url": "https://www.exploit-db.com/exploits/45197/", "name": "45197", "refsource": "EXPLOIT-DB", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in CloudMe before 1.11.0. An unauthenticated remote attacker that can connect to the 'CloudMe Sync' client application listening on port 8888 can send a malicious payload causing a buffer overflow condition. This will result in an attacker controlling the program\"s execution flow and allowing arbitrary code execution."}]}}
