{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-11206", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "hdfgroup", "product": {"product_data": [{"product_name": "hdf5", "version": {"version_data": [{"version_value": "1.10.2", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-125"}]}]}, "references": {"reference_data": [{"url": "https://github.com/TeamSeri0us/pocs/blob/master/hdf5/README2.md", "name": "https://github.com/TeamSeri0us/pocs/blob/master/hdf5/README2.md", "refsource": "MISC", "tags": []}, {"url": "https://github.com/Twi1ight/fuzzing-pocs/tree/master/hdf5", "name": "https://github.com/Twi1ight/fuzzing-pocs/tree/master/hdf5", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "An out of bounds read was discovered in H5O_fill_new_decode and H5O_fill_old_decode in H5Ofill.c in the HDF HDF5 1.10.2 library. It could allow a remote denial of service or information disclosure attack."}]}}
