{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-17793", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": []}}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://github.com/pypa/virtualenv/issues/1207", "name": "https://github.com/pypa/virtualenv/issues/1207", "refsource": "MISC", "tags": []}, {"url": "https://www.exploit-db.com/exploits/45528/", "name": "45528", "refsource": "EXPLOIT-DB", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "** DISPUTED ** Virtualenv 16.0.0 allows a sandbox escape via 'python $(bash >&2)' and 'python $(rbash >&2)' commands. NOTE: the software maintainer disputes this because the Python interpreter in a virtualenv is supposed to be able to execute arbitrary code."}]}}
