{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-12684", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "civetweb_project", "product": {"product_data": [{"product_name": "civetweb", "version": {"version_data": [{"version_value": "1.10", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-125"}, {"lang": "en", "value": "CWE-200"}]}]}, "references": {"reference_data": [{"url": "https://github.com/civetweb/civetweb/commit/8fd069f6dedb064339f1091069ac96f3f8bdb552", "name": "https://github.com/civetweb/civetweb/commit/8fd069f6dedb064339f1091069ac96f3f8bdb552", "refsource": "MISC", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/civetweb/civetweb/issues/633", "name": "https://github.com/civetweb/civetweb/issues/633", "refsource": "MISC", "tags": ["Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Out-of-bounds Read in the send_ssi_file function in civetweb.c in CivetWeb through 1.10 allows attackers to cause a Denial of Service or Information Disclosure via a crafted SSI file."}]}}
