{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14455", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "linuxsampler", "product": {"product_data": [{"product_name": "libgig", "version": {"version_data": [{"version_value": "4.1.0", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-787"}]}]}, "references": {"reference_data": [{"url": "https://github.com/TeamSeri0us/pocs/blob/master/libgig/README.md", "name": "https://github.com/TeamSeri0us/pocs/blob/master/libgig/README.md", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in libgig 4.1.0. There is an out-of-bounds write in pData[0] access in the function store32 in helper.h."}]}}
