{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14614", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "linux", "product": {"product_data": [{"product_name": "linux_kernel", "version": {"version_data": [{"version_value": "4.17.10", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-476"}]}]}, "references": {"reference_data": [{"url": "http://www.securityfocus.com/bid/104917", "name": "104917", "refsource": "BID", "tags": ["Third Party Advisory", "VDB Entry"]}, {"url": "https://bugzilla.kernel.org/show_bug.cgi?id=200419", "name": "https://bugzilla.kernel.org/show_bug.cgi?id=200419", "refsource": "MISC", "tags": ["Issue Tracking", "Technical Description"]}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in the Linux kernel through 4.17.10. There is an out-of-bounds access in __remove_dirty_segment() in fs/f2fs/segment.c when mounting an f2fs image."}]}}
